de:
  track-team:
    server:
      password:
        testServerPassword

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trackteam
    username: postgres
    password: password
  jpa:
    hibernate:
      # Aktualisiert das Datenbankschema durch JPA beim Servicestart
      ddl-auto: update
    # Gibt SQL-Queries in Stdout aus, wenn true
    show-sql: false
    properties:
      hibernate:
        # Formatiert die im Stdout ausgegebenen SQL-Queries
        format_sql: true
        # Ermittelt den für PostgreSQL passenden Dialect automatisch
        dialect: org.hibernate.dialect.PostgreSQLDialect
